version: "3"
services:
  app:
    image: aniket0808/my-flask-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: form-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  mynetwork:
